#!/usr/bin/php
<?php
/**
* AssetFix
*
* @version $Id$
* @package JoomlaCliTools
* @subpackage AssetFix
* @copyright Copyright 2004 - 2013 Matias Aguirre. All rights reserved.
* @license GNU General Public License version 2 or later.
* @author Matias Aguirre <maguirre@matware.com.ar>
* @link http://www.matware.com.ar
*/
// We are a valid Joomla entry point.
define('_JEXEC', 1);

// Setup the base path related constant.
define('JPATH_BASE', dirname(__FILE__));

// Bootstrap the application.
require dirname(dirname(__FILE__)).'/bootstrap.php';

/**
 * This class checks some common situations that occur when the asset table is corrupted.
 */
// Instantiate the application.
class AssetFix extends JApplicationCli
{
	/**
	 * Overrides the parent doExecute method to run the web application.
	 *
	 * This method should include your custom code that runs the application.
	 *
	 * @return  void
	 *
	 * @since   11.3
	 */

	public function __construct()
	{
		// Call the parent __construct method so it bootstraps the application class.
		parent::__construct();
	
		// Getting the parameters
		$this->params = new JRegistry(new JConfig);

		// Creating first dabatase instance
		$this->_db = JFactory::getDBO();
	}

	protected function doExecute()
	{
		// Backup the tables to modify
		$tables = array('#__assets', '#__categories', '#__content');
		$this->doBackup($tables);

		// Cleanup the asset table
		$this->populateDatabase('./sql/assets.sql');

		// Fixing the extensions assets
		$this->fixExtensionsAssets();

		// Fixing the categories assets
		$this->fixCategoryAssets();

		// Fixing the content assets
		$this->fixContentAssets();
	}

	/**
	 * Backup tables
	 *
	 * @param   array         $tables   Array with the tables to backup
	 * @return	boolean
	 * @since   2.5.0
	 * @throws	Exception
	 */
	protected function doBackup($tables) {

		// Rename the tables
		$count = count($tables);

		for($i=0;$i<$count;$i++) {

			$table = $tables[$i];
			$rename = $tables[$i]."_backup";

			$exists = "";
			$exists = $this->_existsTable($rename);

			if ($exists == 0) {
				$this->_copyTable($table, $rename);
			}
		}

	}

 	/**
	 * existsTable
	 *
	 * @return	boolean
	 * @since 1.1.0
	 * @throws	Exception
	 */
	function _existsTable($table)
	{
		// System configuration.
		$database = $this->get('db');

		$table = preg_replace ('/#__/', $this->_db->getPrefix(), $table);

		/*
		$query->select('COUNT(*) AS count');
		$query->from('information_schema.tables');
		$query->where("table_schema = '{$database}'");
		$query->where("table_name = '{$table}'");
		$this->_db->setQuery($query);		
		*/

		$this->_db->setQuery("SELECT COUNT(*) AS count
			FROM information_schema.tables
			WHERE table_schema = '{$database}'
			AND table_name = '{$table}'");

		return $this->_db->loadResult();		
	}

	/**
	 * Copy table to old site to new site
	 *
	 * @return	boolean
	 * @since 1.1.0
	 * @throws	Exception
	 */
	protected function _copyTable($from, $to=null) {

		// System configuration.
		$database = $this->get('db');

		if (!$to) $to = $from;
		$from = preg_replace ('/#__/', $this->_db->getPrefix(), $from);
		$to = preg_replace ('/#__/', $this->_db->getPrefix(), $to);

		$success = $this->_cloneTable($from, $to);
		if ($success) {
			$query = "INSERT INTO {$to} SELECT * FROM {$from}";
			$this->_db->setQuery($query);
			$this->_db->query();

			// Check for query error.
			$error = $this->_db->getErrorMsg();
			if ($error) {
				throw new Exception($error);
			}
			$success = true;
		}

		return $success;
	}

 	/**
	 * Clone table structure from old site to new site
	 *
	 * @return	boolean
	 * @since 1.1.0
	 * @throws	Exception
	 */
	protected function _cloneTable($from, $to=null, $drop=true) {
		// System configuration.
		$database = $this->get('db');

		if (!$to) $to = $from;
		$from = preg_replace ('/#__/', $this->_db->getPrefix(), $from);
		$to = preg_replace ('/#__/', $this->_db->getPrefix(), $to);

		$exists = $this->_existsTable($from);

		if($exists == 0) {
			$success = false;
		} else {
			$query = "CREATE TABLE {$to} LIKE {$from}";
			$this->_db->setQuery($query);
			$this->_db->query();

			// Check for query error.
			$error = $this->_db->getErrorMsg();

			if ($error) {
				throw new Exception($error);
			}
			$success = true;
		}

		return $success;
	}

 	/**
	 * populateDatabase
	 *
	 * @return	boolean
	 * @since 1.1.0
	 * @throws	Exception
	 */
	function populateDatabase($sqlfile)
	{
		if( !($buffer = file_get_contents($sqlfile)) )
		{
			return -1;
		}

		$queries = $this->_db->splitSql($buffer);

		foreach ($queries as $query)
		{
			$query = trim($query);
			if ($query != '' && $query {0} != '#')
			{
				$this->_db->setQuery($query);
				$this->_db->query();

				// Check for query error.
				$error = $this->_db->getErrorMsg();

				if ($error) {
					throw new Exception($error);
				}

			}
		}

		return true;
	}


	protected function fixExtensionsAssets()
	{
		// Fixing categories assets
		$query = $this->_db->getQuery(true);
		$query->select('name, element');
		$query->from('#__extensions');
		$query->where("type = 'component'");
		$query->where("protected = 0");
		$query->group('element');
		$this->_db->setQuery($query);
		$extensions = $this->_db->loadObjectList();

		// Getting the asset table
		$assetfix = JTable::getInstance('asset');

		foreach($extensions as $extension) {
			$assetfix->id = 0;
			$assetfix->reset();

			$assetfix->loadByName($extension->element);

			if ($assetfix->id == 0) {
				// Setting the name and title
				$assetfix->title = $extension->name;
				$assetfix->name = $extension->element;

				// Getting the original rules
				$query = $this->_db->getQuery(true);
				$query->select('rules');
				$query->from('#__assets_backup');
				$query->where("name = '{$extension->element}'");
				$this->_db->setQuery($query);
				$rules = $this->_db->loadResult();
				$assetfix->rules = $rules !== null ? $rules : '{}';

				// Setting the location of the new category
				$assetfix->setLocation(1, 'last-child');
				$assetfix->store();
			}
		}
	} // end method

	protected function fixCategoryAssets()
	{
		// Fixing categories assets
		$query = $this->_db->getQuery(true);
		$query->select('*');
		$query->from('#__categories');
		$query->where('id != 1');
		$query->order('parent_id');
		$this->_db->setQuery($query);
		$categories = $this->_db->loadObjectList();
	
		foreach($categories as $category) {

			// Fixing name of the extension
			$category->extension = $category->extension == 'com_contact_details' ? 'com_contact' : $category->extension;

			// Getting the asset table
			$assetfix = JTable::getInstance('asset');

			$assetfix->title = $category->title;
			$assetfix->name = "{$category->extension}.category.{$category->id}";

			// Getting the original rules
			$query = $this->_db->getQuery(true);
			$query->select('rules');
			$query->from('#__assets_backup');
			$query->where("name = '{$assetfix->name}'");
			$this->_db->setQuery($query);
			$assetfix->rules = $this->_db->loadResult();

			// Setting the parent
			$parent = 0;
			if ($category->parent_id !== false) {
				if ($category->parent_id == 1) {
					$parentAsset = JTable::getInstance('asset');
					$parentAsset->loadByName($category->extension);
					$parent = $parentAsset->id;
				} else if ($category->parent_id > 1) {
					// Getting the correct parent
					$query = $this->_db->getQuery(true);
					$query->select('a.id');
					$query->from('#__categories AS c');
					$query->join('LEFT', '#__assets AS a ON a.title = c.title');
					$query->where("c.id = {$category->parent_id}");
					$this->_db->setQuery($query);
					$parent = $this->_db->loadResult();
				}

				// Setting the location of the new category
				$assetfix->setLocation($parent, 'last-child');
			}

			$assetfix->store();

			// Fixing the category asset_id
			$query = $this->_db->getQuery(true);
			$query->update($this->_db->quoteName('#__categories'));
			$query->set($this->_db->quoteName('asset_id') . ' = ' . (int)$assetfix->id);
			$query->where('id = ' . (int) $category->id);
			$this->_db->setQuery($query);
			$this->_db->query();
		}
	} //end method

	protected function fixContentAssets()
	{
		// Fixing articles assets
		$query = $this->_db->getQuery(true);
		$query->select('*');
		$query->from('#__content');
		$this->_db->setQuery($query);
		$contents = $this->_db->loadObjectList();


		foreach($contents as $article) {

			// Getting the asset table
			$assetfix = JTable::getInstance('asset');

			$assetfix->title = $article->title;
			$assetfix->name = "com_content.article.{$article->id}";

			// Getting the original rules
			$query = $this->_db->getQuery(true);
			$query->select('rules');
			$query->from('#__assets_backup');
			$query->where("name = '{$assetfix->name}'");
			$this->_db->setQuery($query);
			$assetfix->rules = $this->_db->loadResult();

			// Setting the parent
			$parent = 0;
			if ($article->catid !== false) {

				if ($article->catid == 1) {
					$parentAsset = JTable::getInstance('asset');
					$parentAsset->loadByName('com_content');
					$parent = $parentAsset->id;
				} else if ($article->catid > 1) {
					// Getting the correct parent
					$query = $this->_db->getQuery(true);
					$query->select('a.id');
					$query->from('#__categories AS c');
					$query->join('LEFT', '#__assets AS a ON a.title = c.title');
					$query->where("c.id = {$article->catid}");
					$this->_db->setQuery($query);
					$parent = $this->_db->loadResult();
				}

				// Setting the location of the new category
				$assetfix->setLocation($parent, 'last-child');
			}

			$assetfix->store();

			// Fixing the category asset_id
			$query = $this->_db->getQuery(true);
			$query->update($this->_db->quoteName('#__content'));
			$query->set($this->_db->quoteName('asset_id') . ' = ' . (int)$assetfix->id);
			$query->where('id = ' . (int) $article->id);
			$this->_db->setQuery($query);
			$this->_db->query();
		}

	} // end method

} // end class

// Wrap the execution in a try statement to catch any exceptions thrown anywhere in the script.
try
{
	// Instantiate the application object, passing the class name to JCli::getInstance
	// and use chaining to execute the application.
	JApplicationCli::getInstance('AssetFix')->execute();
}
catch (Exception $e)
{
	// An exception has been caught, just echo the message.
	fwrite(STDOUT, $e->getMessage() . "\n");
	exit($e->getCode());
}
